# Site settings
title: Eric Delagrange
email: delagrangebass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Eric Delagrange, Bass-Baritone
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ericdelagrange.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown